#  For Google App Engine deployment, copy this file to app.yaml
#  and edit as required
#  See http://code.google.com/appengine/docs/python/config/appconfig.html
#  and http://web2py.com/book/default/chapter/11?search=app.yaml

application: testdecisionmaking
version: 8
api_version: 1

# use this line for Python 2.5
#
#runtime: python

# use these lines for Python 2.7
# upload app with: appcfg.py update web2py (where 'web2py' is web2py's root directory)
#
runtime: python27
threadsafe: true    # true for WSGI & concurrent requests (Python 2.7 only)

default_expiration: "24h"   # for static files
auto_id_policy: legacy

libraries:
- name: numpy
  version: "latest"

handlers:

- url: /(.+?)/[^_]*\/?static/_\d.\d.\d\/?(.+)
  static_files: applications/\1/static/\2
  upload: applications/(.+?)/static/(.+)
  secure: optional
  expiration: "365d"

- url: /(.+?)/[^_]*\/?static/?(.+)
  static_files: applications/\1/static/\2
  upload: applications/(.+?)/static/(.+)
  secure: optional

- url: /favicon.ico
  static_files: applications/gdms/static/favicon.ico
  upload: applications/gdms/static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: applications/gdms/static/robots.txt
  upload: applications/gdms/static/robots.txt

- url:  /(.+?)/[^_]*\/?manage/?(.+)
# script: gaehandler.py         # CGI
  script: gaehandler.wsgiapp    # WSGI (Python 2.7 only)
  secure: never

- url:  /(.+?)/[^_]*\/?user/?(.+)
# script: gaehandler.py         # CGI
  script: gaehandler.wsgiapp    # WSGI (Python 2.7 only)
  secure: always

- url:  /(.+?)/[^_]*\/?appadmi?(.+)
# script: gaehandler.py         # CGI
  script: gaehandler.wsgiapp    # WSGI (Python 2.7 only)
  secure: always

- url: .*
# script: gaehandler.py         # CGI
  script: gaehandler.wsgiapp    # WSGI (Python 2.7 only)
#  secure: optional
  secure: never

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (applications/(admin|examples)/.*)|
 ((admin|examples|welcome)\.(w2p|tar))|
 (applications/.*?/(cron|databases|errors|cache|sessions)/.*)|
 ((logs|scripts)/.*)|
 (anyserver\.py)|
 (web2py\.py)|
 ((cgi|fcgi|modpython|wsgi)handler\.py)|
 (epydoc\.(conf|css))|
 (httpserver\.log)|
 (logging\.example\.conf)|
 (route[rs]\.example\.py)|
 (setup_(app|exe)\.py)|
 (splashlogo\.gif)|
 (parameters_\d+\.py)|
 (options_std.py)|
 (gluon/tests/.*)|
 (gluon/(rocket|winservice)\.py)|
 (contrib/(gateways|markdown|memcache|pymysql)/.*)|
 (contrib/(populate|taskbar_widget)\.py)|
 (google_appengine/.*)|
 (.*\.(bak|orig))|
 )$

builtins:
- remote_api: on
- appstats: on
- admin_redirect: on
- deferred: on

